export const POST_LIST_FETCH = 'POST_LIST_FETCH';
export const POST_LIST_ERROR = 'POST_LIST_ERROR';
export const POST_LIST_SUCCESS = 'POST_LIST_SUCCESS';

export const POST_CREATE_FETCH = 'POST_CREATE_FETCH';
export const POST_CREATE_ERROR = 'POST_CREATE_ERROR';
export const POST_CREATE_SUCCESS = 'POST_CREATE_SUCCESS';

export const POST_UPDATE_FETCH = 'POST_UPDATE_FETCH';
export const POST_UPDATE_ERROR = 'POST_UPDATE_ERROR';
export const POST_UPDATE_SUCCESS = 'POST_UPDATE_SUCCESS';

export const POST_DELETE_FETCH = 'POST_DELETE_FETCH';
export const POST_DELETE_ERROR = 'POST_DELETE_ERROR';
export const POST_DELETE_SUCCESS = 'POST_DELETE_SUCCESS';

export const POST_ITEM_FETCH = 'POST_ITEM_FETCH';
export const POST_ITEM_ERROR = 'POST_ITEM_ERROR';
export const POST_ITEM_SUCCESS = 'POST_ITEM_SUCCESS';

export const POST_VOTE_FETCH = 'POST_VOTE_FETCH';
export const POST_VOTE_ERROR = 'POST_VOTE_ERROR';
export const POST_VOTE_SUCCESS = 'POST_VOTE_SUCCESS';

export const COMMENT_LIST_FETCH = 'COMMENT_LIST_FETCH';
export const COMMENT_LIST_ERROR = 'COMMENT_LIST_ERROR';
export const COMMENT_LIST_SUCCESS = 'COMMENT_LIST_SUCCESS';

export const COMMENT_CREATE_FETCH = 'COMMENT_CREATE_FETCH';
export const COMMENT_CREATE_ERROR = 'COMMENT_CREATE_ERROR';
export const COMMENT_CREATE_SUCCESS = 'COMMENT_CREATE_SUCCESS';

export const COMMENT_UPDATE_FETCH = 'COMMENT_UPDATE_FETCH';
export const COMMENT_UPDATE_ERROR = 'COMMENT_UPDATE_ERROR';
export const COMMENT_UPDATE_SUCCESS = 'COMMENT_UPDATE_SUCCESS';

export const COMMENT_DELETE_FETCH = 'COMMENT_DELETE_FETCH';
export const COMMENT_DELETE_ERROR = 'COMMENT_DELETE_ERROR';
export const COMMENT_DELETE_SUCCESS = 'COMMENT_DELETE_SUCCESS';

export const COMMENT_VOTE_FETCH = 'COMMENT_VOTE_FETCH';
export const COMMENT_VOTE_ERROR = 'COMMENT_VOTE_ERROR';
export const COMMENT_VOTE_SUCCESS = 'COMMENT_VOTE_SUCCESS';
